name: Build and Deploy

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
     contents: 'read'
     id-token: 'write'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'pokemon-weather-companion'
          token_format: access_token
          workload_identity_provider: 'projects/808521182590/locations/global/workloadIdentityPools/github/providers/meike'
          service_account: 'pwc-sa@pokemon-weather-companion.iam.gserviceaccount.com'

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-south1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env: 
          POSTGRES_LOCAL_PASSWORD: ${{ secrets.POSTGRES_LOCAL_PASSWORD }}
          POKE_GO_PAL_DATABASE_NAME: ${{ secrets.POKE_GO_PAL_DATABASE_NAME }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        with:
          push: true
          tags: us-south1-docker.pkg.dev/pokemon-weather-companion/meike/pokemon-weather-companion:latest
          build-args: 
            - postgres_local_password=$POSTGRES_LOCAL_PASSWORD
            - poke_go_pal_database_name=$POKE_GO_PAL_DATABASE_NAME
            - weather_api_key=$WEATHER_API_KEY
        
          