name: Build and Deploy

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'pokemon-weather-companion'
          token_format: access_token
          workload_identity_provider: 'projects/808521182590/locations/global/workloadIdentityPools/github-actions-wip/providers/github'

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-south1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: us-south1-docker.pkg.dev/pokemon-weather-companion/meike/pokemon-weather-companion:latest